apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-consumer
  labels:
    app: tx-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tx-consumer
  template:
    metadata:
      labels:
        app: tx-consumer
    spec:
      containers:
      - name: tx-consumer
        image: pivotalrabbitmq/perf-test:latest
        args:
          - --producers
          - "0"
          - --consumers
          - "1"
          - --flag
          - persistent
          - --exchange
          - incoming-transaction
          - --queue
          - transactions
          - --metrics-prometheus
          - --auto-delete
          - "false"
          - --uri
          - $(RABBITMQ_AMQP_URI)
        env:
        - name: RABBITMQ_AMQP_URI
          valueFrom:
            configMapKeyRef:
              name: consumer-config
              key: RABBITMQ_AMQP_URI
        ports:
        - containerPort: 8080  # for prometheus exporter
